[theme]
primaryColor = "#0b3d91"
backgroundColor = "#f9fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#222222"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[ui]
layout = "wide"
