[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"            # Pilihan: "light" atau "dark"
primaryColor = "#0b3d91"   # Biru Pro untuk aksen tombol/link
backgroundColor = "#f9fafc"  # Background app (putih lembut)
secondaryBackgroundColor = "#ffffff"  # Background sidebar/komponen lain
textColor = "#222222"        # Warna teks utama
font = "sans serif"         # Pilihan font: "sans serif", "serif", "monospace"

[client]
tooltipDelay = 500           # Delay tooltip (ms)
tooltipHoverDelay = 100      # Hover delay sebelum tooltip muncul (ms)

[logger]
level = "warning"

[deprecation]
showfileUploaderEncoding = false