# .streamlit/secrets.toml

# === Application Secrets Template ===
# Gunakan file ini untuk menyimpan credential sensitif atau konfigurasi rahasia.
# Saat deploy di Streamlit Cloud, masukkan key-value ini via Dashboard (Secrets Manager).

# === Example Usage ===
# import streamlit as st
# API_KEY = st.secrets["API_KEY"]
# DB_PASSWORD = st.secrets["DB_PASSWORD"]

# === Secrets ===

[general]
PROJECT_NAME = "Simulasi Kalkulasi Pemilu 2029"
ENVIRONMENT = "development"  # atau "production"

# Jika di masa depan pakai API eksternal:
[api_keys]
#example_api = "your-api-key-here"

# Jika di masa depan pakai Database:
[database]
host = "localhost"
port = "5432"
user = "username"
password = "password"
database = "database_name"

# === Notes ===
# - Jangan pernah upload file .streamlit/secrets.toml ke GitHub public.
# - Streamlit Cloud akan mengenali file ini otomatis di deploy.
# - Untuk security, hanya simpan secrets di platform secure atau manual saat deploy.
